export const LINEID_NEWLINE_AFTER = 'line:NEWLINE_AFTER'
export const LINEID_NEWLINE_BEFORE = 'line:NEWLINE_BEFORE'
export const LINEID_INITIAL = 'line:INITIAL'
export const preserveLineIds = [LINEID_NEWLINE_AFTER, LINEID_NEWLINE_BEFORE, LINEID_INITIAL]
